### ISSUE TITLE
Тормоза при большом контексте и нескольких шаблонах

### ISSUE THREAD

**Issue by BelirafoN** [f-o-r/yate-playground#6]
Если в контекст кинуть средний/большой объект, или в редакторе разместить несколько шаблонов с аплаями, плейграунд начинает ощутимо тормозить. Тормозит порою так, что печатать сложно.

Сейчас трансформация запускается сразу после какого-либо ввода. Думаю тротлинг на трансформацию по вводу может решить проблему с тормозами.

**Comment by ilya-m32** [comment]
Не сталкивался, но вполне может быть. 
Постараюсь запилить на следующих выходных.

**Comment by myshov** [comment]
merged
